/**
 * KeyEngine.test.js
 * Verifies all 144 key pairs against the canonical matrix
 * produced by docs/mapcopy_layout.py
 *
 * Run: npx jest tests/KeyEngine.test.js
 */

import { KeyEngine } from '../src/engine/KeyEngine.js';

// Canonical layout — must match docs/layout.json exactly
const LAYOUT = [
  { t: 'u', chars: ['u','v','w','x',    '_','=','<','>',    'U','V','W','X'] },
  { t: 'i', chars: ['i','j','k','l',    '/','\\','(',')',   'I','J','K','L'] },
  { t: 'o', chars: ['q','r','s','t',    '^','~','[',']',    'Q','R','S','T'] },
  { t: 'p', chars: ['+','-','?','!',    '|',';',':','\'',   '"','`','{','}'] },
  { t: 'j', chars: ['a','b','c','d',    '^S','^W','^T','^N','A','B','C','D'] },
  { t: 'k', chars: ['e','f','g','h',    '^F','^H','^R','^B','E','F','G','H'] },
  { t: 'l', chars: ['m','n','o','p',    '^D','^L','^K','^P','M','N','O','P'] },
  { t: 'ö', chars: ['y','z',',','.',    '^G','^U','^I','^E','Y','Z','…','•'] },
  { t: 'n', chars: ['0','1','2','3',    'SP','TAB','ENT','ESC','BS','DEL','HOME','END'] },
  { t: 'm', chars: ['4','5','6','7',    'PGUP','PGDN','INS','←','→','↑','↓','F1'] },
  { t: ',', chars: ['8','9','@','#',    'F2','F3','F4','F5','F6','F7','F8','F9'] },
  { t: '.', chars: ['$','%','&','*',    'F10','F11','F12','^C','^V','^X','^Z','^A'] },
];

// Canonical 12×12 matrix — generated by mapcopy_layout.py
// Row = first key, Col = second key, order matches LAYOUT above
const MATRIX = [
  ['u','v','w','x',    '_','=','<','>',    'U','V','W','X'],
  ['l','i','j','k',    ')','/','\\'  ,'(', 'L','I','J','K'],
  ['s','t','q','r',    '[',']','^','~',    'S','T','Q','R'],
  ['-','?','!','+',    ';',':','\'','|',   '`','{','}','"'],
  ['A','B','C','D',    'a','b','c','d',    '^S','^W','^T','^N'],
  ['H','E','F','G',    'h','e','f','g',    '^B','^F','^H','^R'],
  ['O','P','M','N',    'o','p','m','n',    '^K','^P','^D','^L'],
  ['Z','…','•','Y',    'z',',','.','y',    '^U','^I','^E','^G'],
  ['SP','TAB','ENT','ESC', 'BS','DEL','HOME','END', '0','1','2','3'],
  ['←','PGUP','PGDN','INS','F1','→','↑','↓',       '7','4','5','6'],
  ['F4','F5','F2','F3', 'F8','F9','F6','F7',        '@','#','8','9'],
  ['F11','F12','^C','F10', '^X','^Z','^A','^V',     '%','&','*','$'],
];

const KEYS = LAYOUT.map(k => k.t);

describe('KeyEngine — formula', () => {
  const engine = new KeyEngine();
  engine.loadLayout(LAYOUT);

  test('loads 12 keys', () => {
    expect(engine.triggers.length).toBe(12);
  });

  // Spot-check examples from LOGIC.md
  const examples = [
    ['j', 'j', 'a'],
    ['i', 'u', 'l'],
    ['j', 'l', 'c'],
    ['o', 'p', 'r'],
    ['j', 'n', 'A'],
    ['j', 'u', 'A'],
    ['n', 'j', 'BS'],
    ['n', 'u', 'SP'],
  ];

  test.each(examples)('%s → %s = %s', (first, second, expected) => {
    const result = engine.resolve(first, second);
    expect(result.char).toBe(expected);
  });

  // Full 144-pair matrix verification
  describe('full 12×12 matrix', () => {
    KEYS.forEach((firstT, fi) => {
      KEYS.forEach((secondT, si) => {
        const expected = MATRIX[fi][si];
        test(`${firstT}→${secondT} = '${expected}'`, () => {
          const result = engine.resolve(firstT, secondT);
          expect(result.char).toBe(expected);
        });
      });
    });
  });
});

describe('KeyEngine — state machine', () => {
  let engine;
  beforeEach(() => {
    engine = new KeyEngine();
    engine.loadLayout(LAYOUT);
  });

  test('first press → pending', () => {
    const evt = engine.press('j');
    expect(evt.type).toBe('pending');
    expect(engine.pending).toBe('j');
    expect(engine.committed).toEqual([]);
  });

  test('second press → commit', () => {
    engine.press('j');
    const evt = engine.press('j');
    expect(evt.type).toBe('commit');
    expect(evt.char).toBe('a');
    expect(engine.pending).toBeNull();
    expect(engine.text).toBe('a');
  });

  test('j → l = c', () => {
    engine.press('j');
    const evt = engine.press('l');
    expect(evt.char).toBe('c');
  });

  test('space while pending commits chars[0]', () => {
    engine.press('j');
    const evt = engine.space();
    expect(evt.type).toBe('commit');
    expect(evt.char).toBe('a');
    expect(engine.pending).toBeNull();
  });

  test('space while idle duplicates last char', () => {
    engine.press('j'); engine.press('j'); // commits 'a'
    const evt = engine.space();
    expect(evt.type).toBe('duplicate');
    expect(evt.char).toBe('a');
    expect(engine.text).toBe('aa');
  });

  test('space while empty is noop', () => {
    const evt = engine.space();
    expect(evt.type).toBe('noop');
  });

  test('backspace cancels pending', () => {
    engine.press('j');
    const evt = engine.backspace();
    expect(evt.type).toBe('cancel');
    expect(engine.pending).toBeNull();
    expect(engine.committed).toEqual([]);
  });

  test('backspace deletes last committed', () => {
    engine.press('j'); engine.press('j'); // 'a'
    engine.press('k'); engine.press('k'); // 'e'
    engine.backspace();
    expect(engine.text).toBe('a');
  });

  test('backspace while empty is noop', () => {
    const evt = engine.backspace();
    expect(evt.type).toBe('noop');
  });

  test('previewAll returns 12 entries when pending', () => {
    const map = engine.previewAll('j');
    expect(Object.keys(map).length).toBe(12);
    expect(map['j'].char).toBe('a');
    expect(map['l'].char).toBe('c');
    expect(map['n'].char).toBe('A');
  });

  test('reset clears state', () => {
    engine.press('j'); engine.press('j');
    engine.press('k');
    engine.reset();
    expect(engine.pending).toBeNull();
    expect(engine.committed).toEqual([]);
  });
});

describe('Layout — validation', () => {
  const { Layout } = require('../src/engine/Layout.js');

  test('valid layout loads cleanly', () => {
    const layout = new Layout();
    const result = layout.load(LAYOUT);
    expect(result.ok).toBe(true);
    expect(result.errors).toEqual([]);
  });

  test('rejects wrong key count', () => {
    const layout = new Layout();
    const result = layout.load(LAYOUT.slice(0, 10));
    expect(result.ok).toBe(false);
  });

  test('rejects duplicate characters', () => {
    const layout  = new Layout();
    const broken  = LAYOUT.map((k, i) => i === 1
      ? { ...k, chars: [...LAYOUT[0].chars] }  // duplicate key 0's chars
      : k
    );
    const result = layout.load(broken);
    expect(result.ok).toBe(false);
    expect(result.errors.some(e => e.includes('Duplicate'))).toBe(true);
  });
});
