/**
 * Layout.js
 * Loads, validates, and exposes the MapCopy layout.
 * Source of truth: docs/layout.json (generated by docs/mapcopy_layout.py)
 */

const REQUIRED_CHARS_PER_KEY = 12;
const REQUIRED_KEY_COUNT     = 12;

export class Layout {
  constructor() {
    this._raw   = null;
    this._valid = false;
    this._errors = [];
  }

  /**
   * Load from a plain JS array (already parsed JSON).
   * Returns { ok, errors }
   */
  load(layoutArray) {
    this._errors = [];
    this._raw    = null;
    this._valid  = false;

    if (!Array.isArray(layoutArray)) {
      this._errors.push('Layout must be an array');
      return this._result();
    }
    if (layoutArray.length !== REQUIRED_KEY_COUNT) {
      this._errors.push(`Expected ${REQUIRED_KEY_COUNT} keys, got ${layoutArray.length}`);
      return this._result();
    }

    const seen = new Set();
    for (const [i, key] of layoutArray.entries()) {
      if (typeof key.t !== 'string') {
        this._errors.push(`Key ${i}: missing trigger string "t"`);
        continue;
      }
      if (!Array.isArray(key.chars) || key.chars.length !== REQUIRED_CHARS_PER_KEY) {
        this._errors.push(`Key "${key.t}": must have exactly ${REQUIRED_CHARS_PER_KEY} chars`);
        continue;
      }
      for (const char of key.chars) {
        if (seen.has(char)) {
          this._errors.push(`Duplicate character "${char}" in key "${key.t}"`);
        }
        seen.add(char);
      }
    }

    if (this._errors.length === 0) {
      this._raw   = layoutArray;
      this._valid = true;
    }

    return this._result();
  }

  /**
   * Fetch layout.json from a URL and load it.
   */
  async fetch(url = './docs/layout.json') {
    try {
      const res  = await window.fetch(url);
      const data = await res.json();
      return this.load(data);
    } catch (e) {
      this._errors = [`Failed to fetch layout: ${e.message}`];
      return this._result();
    }
  }

  get isValid()  { return this._valid; }
  get errors()   { return [...this._errors]; }
  get raw()      { return this._raw ? [...this._raw] : null; }

  _result() {
    return { ok: this._valid, errors: this._errors };
  }
}
